pub mod admin_institution_service;
pub mod record_service;
pub mod zk_proof_service;
pub mod crypto_service;
pub mod dashboard_service;
pub mod storage_service;
pub mod credit_service;
pub mod reports_storage;
pub mod token_service;
