[package]
name = "token_backend"  # 注意这里改为 token_backend
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.6"
ic-cdk = "0.11.6"
ic-cdk-macros = "0.8.1"
serde = { version = "1.0", features = ["derive"] }