[package]
name = "decent_credit_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
<<<<<<< HEAD
candid = "0.9.9"
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
ic-stable-structures = "0.5.6"
serde = "1.0.188"
serde_derive = "1.0.188"
=======
# IC 相关依赖
candid = { version = "0.9.9", features = ["parser"] }
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
ic-stable-structures = "0.5.6"

# 序列化相关
serde = { version = "1.0.188", features = ["derive"], default-features = false }
bincode = { version = "1.3", default-features = false }

# 密码学和工具
sha2 = { version = "0.10.7", default-features = false }
ff = { version = "0.12", default-features = false }
hex = "0.4.3"
aes-gcm = { version = "0.10.2", default-features = false, features = ["alloc", "aes"] }
ed25519-dalek = { version = "2.0", default-features = false, features = ["rand_core"] }
base64 = { version = "0.21.4", default-features = false, features = ["alloc"] }

# 随机数生成
getrandom = { version = "0.2.10", default-features = false, features = ["js"] }
rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }
rand_chacha = { version = "0.3.1", default-features = false }

# 零知识证明相关依赖
pairing = { version = "0.23", default-features = false }
bellman = { version = "0.13.1", default-features = false, features = ["groth16"] }
bls12_381 = { version = "0.7.1", default-features = false, features = ["pairings"] }

# 时间处理
chrono = { version = "0.4", default-features = false, features = ["serde", "wasmbind"] }

# 日志系统 - WebAssembly 适配
log = { version = "0.4", default-features = false }
# env_logger 在 wasm 环境中通常不需要，如果你需要在 wasm 中记录日志，
# 建议使用 wasm-logger 或 console_log
wasm-logger = "0.2"

[target.wasm32-unknown-unknown]
# wasm 特定的优化设置
rustflags = [
    "-C", "link-arg=-zstack-size=32768",
    "-C", "link-arg=--import-memory",
]
>>>>>>> dec-test
